# Generated by Django 5.2.7 on 2025-10-27 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('latitude', models.FloatField(help_text='Market latitude')),
                ('longitude', models.FloatField(help_text='Market longitude')),
                ('market_type', models.CharField(choices=[('wholesale', 'Wholesale Market'), ('retail', 'Retail Market'), ('collection', 'Collection Center'), ('cooperative', 'Cooperative Market')], max_length=20)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('operating_days', models.CharField(blank=True, help_text='e.g., Monday-Friday', max_length=100)),
                ('has_cold_storage', models.BooleanField(default=False)),
                ('has_grading_facility', models.BooleanField(default=False)),
                ('has_packaging_facility', models.BooleanField(default=False)),
                ('transportation_available', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['district', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MarketSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_latitude', models.FloatField()),
                ('search_longitude', models.FloatField()),
                ('search_district', models.CharField(blank=True, max_length=100)),
                ('crop_to_sell', models.CharField(blank=True, max_length=100)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('search_date', models.DateTimeField(auto_now_add=True)),
                ('nearest_market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market_finder.market')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-search_date'],
            },
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('price_per_kg', models.FloatField(help_text='Price per kg in NPR')),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('price_date', models.DateField()),
                ('source', models.CharField(blank=True, help_text='Source of price information', max_length=100)),
                ('quality_grade', models.CharField(choices=[('premium', 'Premium'), ('standard', 'Standard'), ('below_standard', 'Below Standard')], default='standard', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='market_finder.market')),
            ],
            options={
                'ordering': ['-price_date', 'crop_name'],
                'unique_together': {('market', 'crop_name', 'price_date', 'quality_grade')},
            },
        ),
    ]
