from django.db import models
from authentication.models import CustomUser

class Crop(models.Model):
    """
    Model to store crop information and requirements
    """
    name = models.CharField(max_length=100, unique=True)
    scientific_name = models.CharField(max_length=150, blank=True)
    description = models.TextField(blank=True)
    
    # Optimal soil conditions
    min_ph = models.FloatField(help_text="Minimum pH level")
    max_ph = models.FloatField(help_text="Maximum pH level")
    min_nitrogen = models.FloatField(help_text="Minimum nitrogen content (mg/kg)")
    max_nitrogen = models.FloatField(help_text="Maximum nitrogen content (mg/kg)")
    min_phosphorus = models.FloatField(help_text="Minimum phosphorus content (mg/kg)")
    max_phosphorus = models.FloatField(help_text="Maximum phosphorus content (mg/kg)")
    min_potassium = models.FloatField(help_text="Minimum potassium content (mg/kg)")
    max_potassium = models.FloatField(help_text="Maximum potassium content (mg/kg)")
    min_rainfall = models.FloatField(help_text="Minimum rainfall (mm)")
    max_rainfall = models.FloatField(help_text="Maximum rainfall (mm)")
    
    # Growing season
    SEASONS = [
        ('spring', 'Spring'),
        ('summer', 'Summer'),
        ('monsoon', 'Monsoon'),
        ('autumn', 'Autumn'),
        ('winter', 'Winter'),
    ]
    suitable_seasons = models.CharField(max_length=200, help_text="Comma-separated seasons")
    
    # Additional information
    growth_duration = models.IntegerField(help_text="Growth duration in days", null=True, blank=True)
    yield_per_hectare = models.FloatField(help_text="Average yield per hectare (kg)", null=True, blank=True)
    market_price = models.FloatField(help_text="Average market price per kg (NPR)", null=True, blank=True)
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['name']

class SoilData(models.Model):
    """
    Model to store soil test data from farmers
    """
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='soil_data')
    
    # Soil parameters
    ph_level = models.FloatField(help_text="Soil pH level")
    nitrogen = models.FloatField(help_text="Nitrogen content (mg/kg)")
    phosphorus = models.FloatField(help_text="Phosphorus content (mg/kg)")
    potassium = models.FloatField(help_text="Potassium content (mg/kg)")
    rainfall = models.FloatField(help_text="Annual rainfall (mm)")
    
    # Location and season
    district = models.CharField(max_length=100)
    season = models.CharField(max_length=20, choices=Crop.SEASONS)
    
    # Metadata
    test_date = models.DateTimeField(auto_now_add=True)
    notes = models.TextField(blank=True, help_text="Additional notes from farmer")
    
    def __str__(self):
        return f"{self.user.username} - {self.district} - {self.test_date.date()}"
    
    class Meta:
        ordering = ['-test_date']

class CropRecommendation(models.Model):
    """
    Model to store crop recommendations generated by the system
    """
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='recommendations')
    soil_data = models.ForeignKey(SoilData, on_delete=models.CASCADE, related_name='recommendations')
    
    # Recommended crops (can be multiple)
    recommended_crops = models.ManyToManyField(Crop, through='RecommendationScore')
    
    # Algorithm details
    algorithm_used = models.CharField(max_length=50, default='Decision Tree')
    confidence_score = models.FloatField(help_text="Confidence score of recommendation (0-1)")
    
    # Metadata
    created_at = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    
    def __str__(self):
        return f"Recommendation for {self.user.username} - {self.created_at.date()}"
    
    class Meta:
        ordering = ['-created_at']

class RecommendationScore(models.Model):
    """
    Through model to store individual crop scores in recommendation
    """
    recommendation = models.ForeignKey(CropRecommendation, on_delete=models.CASCADE)
    crop = models.ForeignKey(Crop, on_delete=models.CASCADE)
    score = models.FloatField(help_text="Suitability score for this crop (0-1)")
    ranking = models.IntegerField(help_text="Ranking position (1 = best)")
    
    class Meta:
        unique_together = ['recommendation', 'crop']
        ordering = ['ranking']
