# Generated by Django 5.2.7 on 2025-10-27 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('scientific_name', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('min_ph', models.FloatField(help_text='Minimum pH level')),
                ('max_ph', models.FloatField(help_text='Maximum pH level')),
                ('min_nitrogen', models.FloatField(help_text='Minimum nitrogen content (mg/kg)')),
                ('max_nitrogen', models.FloatField(help_text='Maximum nitrogen content (mg/kg)')),
                ('min_phosphorus', models.FloatField(help_text='Minimum phosphorus content (mg/kg)')),
                ('max_phosphorus', models.FloatField(help_text='Maximum phosphorus content (mg/kg)')),
                ('min_potassium', models.FloatField(help_text='Minimum potassium content (mg/kg)')),
                ('max_potassium', models.FloatField(help_text='Maximum potassium content (mg/kg)')),
                ('min_rainfall', models.FloatField(help_text='Minimum rainfall (mm)')),
                ('max_rainfall', models.FloatField(help_text='Maximum rainfall (mm)')),
                ('suitable_seasons', models.CharField(help_text='Comma-separated seasons', max_length=200)),
                ('growth_duration', models.IntegerField(blank=True, help_text='Growth duration in days', null=True)),
                ('yield_per_hectare', models.FloatField(blank=True, help_text='Average yield per hectare (kg)', null=True)),
                ('market_price', models.FloatField(blank=True, help_text='Average market price per kg (NPR)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CropRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_used', models.CharField(default='Decision Tree', max_length=50)),
                ('confidence_score', models.FloatField(help_text='Confidence score of recommendation (0-1)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='Suitability score for this crop (0-1)')),
                ('ranking', models.IntegerField(help_text='Ranking position (1 = best)')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop_recommendation.crop')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop_recommendation.croprecommendation')),
            ],
            options={
                'ordering': ['ranking'],
                'unique_together': {('recommendation', 'crop')},
            },
        ),
        migrations.AddField(
            model_name='croprecommendation',
            name='recommended_crops',
            field=models.ManyToManyField(through='crop_recommendation.RecommendationScore', to='crop_recommendation.crop'),
        ),
        migrations.CreateModel(
            name='SoilData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_level', models.FloatField(help_text='Soil pH level')),
                ('nitrogen', models.FloatField(help_text='Nitrogen content (mg/kg)')),
                ('phosphorus', models.FloatField(help_text='Phosphorus content (mg/kg)')),
                ('potassium', models.FloatField(help_text='Potassium content (mg/kg)')),
                ('rainfall', models.FloatField(help_text='Annual rainfall (mm)')),
                ('district', models.CharField(max_length=100)),
                ('season', models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('monsoon', 'Monsoon'), ('autumn', 'Autumn'), ('winter', 'Winter')], max_length=20)),
                ('test_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes from farmer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-test_date'],
            },
        ),
        migrations.AddField(
            model_name='croprecommendation',
            name='soil_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='crop_recommendation.soildata'),
        ),
    ]
