# Generated by Django 5.2.7 on 2025-12-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soildata',
            name='season',
            field=models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Autumn', 'Autumn'), ('Winter', 'Winter')], max_length=20),
        ),
    ]
