# Generated by Django 5.2.7 on 2025-12-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_recommendation', '0002_alter_soildata_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='soildata',
            name='humidity',
            field=models.FloatField(blank=True, help_text='Humidity (%)', null=True),
        ),
        migrations.AddField(
            model_name='soildata',
            name='temperature',
            field=models.FloatField(blank=True, help_text='Temperature (°C)', null=True),
        ),
    ]
